// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.26.2";

// src/lib/mcp/tools/get-my-profile.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.26.2";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.58.0";
function runtimeEnv(name) {
  const runtime = globalThis;
  return runtime.Deno?.env?.get?.(name) ?? runtime.process?.env?.[name];
}
function configuredEnv(names) {
  for (const name of names) {
    const value = runtimeEnv(name)?.trim();
    if (value) return value;
  }
  return void 0;
}
function supabaseProjectUrl() {
  const url = configuredEnv(["SUPABASE_URL", "VITE_SUPABASE_URL"]);
  if (!url) throw new Error("SUPABASE_URL (or VITE_SUPABASE_URL) is required");
  return url;
}
function supabasePublishableKey() {
  const direct = configuredEnv([
    "SUPABASE_PUBLISHABLE_KEY",
    "VITE_SUPABASE_PUBLISHABLE_KEY"
  ]);
  if (direct) return direct;
  const keyset = runtimeEnv("SUPABASE_PUBLISHABLE_KEYS");
  if (keyset) {
    try {
      const parsed = JSON.parse(keyset);
      if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
        const keys = parsed;
        const key = [keys.default, ...Object.values(keys)].find((v) => typeof v === "string" && v.trim().startsWith("sb_publishable_"))?.trim();
        if (key) return key;
      }
    } catch {
    }
  }
  const legacy = configuredEnv(["SUPABASE_ANON_KEY", "VITE_SUPABASE_ANON_KEY"]);
  if (legacy) return legacy;
  throw new Error("SUPABASE_PUBLISHABLE_KEY, SUPABASE_PUBLISHABLE_KEYS, or SUPABASE_ANON_KEY is required");
}
function supabaseForUser(ctx) {
  const token = ctx.getToken();
  if (!token) throw new Error("supabaseForUser requires a verified OAuth token");
  return createClient(supabaseProjectUrl(), supabasePublishableKey(), {
    global: { headers: { Authorization: `Bearer ${token}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}

// src/lib/mcp/tools/get-my-profile.ts
var get_my_profile_default = defineTool({
  name: "get_my_profile",
  title: "Get my profile",
  description: "Get the signed-in user's Nexora profile (username, display name, status, bio).",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("profiles").select("username, display_name, bio, status, location, is_verified, preferred_language").eq("user_id", ctx.getUserId()).maybeSingle();
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    if (!data) {
      return { content: [{ type: "text", text: "No profile found for this user." }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { profile: data }
    };
  }
});

// src/lib/mcp/tools/list-contacts.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z } from "npm:zod@^3.25.76";
var list_contacts_default = defineTool2({
  name: "list_contacts",
  title: "List contacts",
  description: "List the signed-in user's saved Nexora contacts.",
  inputSchema: {
    limit: z.number().int().min(1).max(100).default(50).describe("Maximum number of contacts to return.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("contacts").select("id, contact_user_id, contact_name, is_favourite, created_at").eq("user_id", ctx.getUserId()).order("created_at", { ascending: false }).limit(limit ?? 50);
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { contacts: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-conversations.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z as z2 } from "npm:zod@^3.25.76";
var list_conversations_default = defineTool3({
  name: "list_conversations",
  title: "List conversations",
  description: "List the signed-in user's Nexora conversations (direct chats and groups), most recently updated first.",
  inputSchema: {
    limit: z2.number().int().min(1).max(50).default(20).describe("Maximum number of conversations to return.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data: parts, error: partsError } = await supabase.from("conversation_participants").select("conversation_id").eq("user_id", ctx.getUserId());
    if (partsError) {
      return { content: [{ type: "text", text: partsError.message }], isError: true };
    }
    const ids = (parts ?? []).map((p) => p.conversation_id);
    if (ids.length === 0) {
      return { content: [{ type: "text", text: "No conversations." }], structuredContent: { conversations: [] } };
    }
    const { data, error } = await supabase.from("conversations").select("id, is_group, group_name, created_at, updated_at").in("id", ids).order("updated_at", { ascending: false }).limit(limit ?? 20);
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { conversations: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-messages.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z as z3 } from "npm:zod@^3.25.76";
var get_messages_default = defineTool4({
  name: "get_messages",
  title: "Get messages",
  description: "Read the most recent messages in one of the signed-in user's conversations.",
  inputSchema: {
    conversation_id: z3.string().uuid().describe("The conversation to read messages from."),
    limit: z3.number().int().min(1).max(100).default(30).describe("Maximum number of messages to return.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ conversation_id, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("messages").select("id, sender_id, content, message_type, created_at").eq("conversation_id", conversation_id).order("created_at", { ascending: false }).limit(limit ?? 30);
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    const messages = (data ?? []).slice().reverse();
    return {
      content: [{ type: "text", text: JSON.stringify(messages) }],
      structuredContent: { messages }
    };
  }
});

// src/lib/mcp/tools/send-message.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z as z4 } from "npm:zod@^3.25.76";
var send_message_default = defineTool5({
  name: "send_message",
  title: "Send message",
  description: "Send a text message as the signed-in user into one of their Nexora conversations.",
  inputSchema: {
    conversation_id: z4.string().uuid().describe("The conversation to send the message to."),
    content: z4.string().trim().min(1).max(4e3).describe("The message text to send.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async ({ conversation_id, content }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("messages").insert({
      conversation_id,
      sender_id: ctx.getUserId(),
      content,
      message_type: "text"
    }).select("id, conversation_id, content, created_at").single();
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: `Message sent (${data.id}).` }],
      structuredContent: { message: data }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "jtlnhmpxytlgljnuspan";
var mcp_default = defineMcp({
  name: "nexoraai",
  title: "NexoraAI",
  version: "0.1.0",
  instructions: "Tools for Nexora, a messaging app. Read the signed-in user's profile and contacts, list their conversations, read recent messages, and send new messages. All access is scoped to the authenticated user.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [get_my_profile_default, list_contacts_default, list_conversations_default, get_messages_default, send_message_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.26.2/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
